version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/Doc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cmake"
    directory: "/"
    schedule:
      interval: "weekly"
